# Generated by Django 5.1.15 on 2026-05-30 01:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical', '0001_initial'),
        ('owners', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('date', models.DateField(auto_now_add=True, verbose_name='tarih')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='toplam')),
                ('status', models.CharField(choices=[('paid', 'Ödendi'), ('partial', 'Kısmi ödendi'), ('pending', 'Bekliyor')], db_index=True, default='pending', max_length=10, verbose_name='durum')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='açıklama')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('examination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='medical.examination', verbose_name='muayene')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='owners.owner', verbose_name='sahip')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='patients.patient', verbose_name='hayvan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'İşlem / Ücret',
                'verbose_name_plural': 'İşlemler / Ücretler',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='tutar')),
                ('method', models.CharField(choices=[('cash', 'Nakit'), ('card', 'Kart'), ('transfer', 'Havale/EFT'), ('unpaid', 'Ödenmedi')], default='cash', max_length=10, verbose_name='yöntem')),
                ('paid_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='ödeme zamanı')),
                ('reference', models.CharField(blank=True, max_length=120, verbose_name='referans')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='not')),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.charge')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'Tahsilat',
                'verbose_name_plural': 'Tahsilatlar',
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('name', models.CharField(max_length=160, verbose_name='ad')),
                ('kind', models.CharField(choices=[('service', 'Hizmet'), ('product', 'Ürün')], default='service', max_length=10, verbose_name='tür')),
                ('default_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='varsayılan fiyat')),
                ('active', models.BooleanField(default=True, verbose_name='aktif')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'Hizmet / Ürün',
                'verbose_name_plural': 'Hizmetler / Ürünler',
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChargeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('description', models.CharField(max_length=200, verbose_name='açıklama')),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='adet')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='birim fiyat')),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='satır tutarı')),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.charge')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='billing.serviceitem')),
            ],
            options={
                'verbose_name': 'İşlem Satırı',
                'verbose_name_plural': 'İşlem Satırları',
            },
        ),
    ]
