# Generated by Django 5.1.15 on 2026-05-30 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('owners', '0001_initial'),
        ('patients', '0001_initial'),
        ('vaccines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('key', models.SlugField(max_length=60, unique=True, verbose_name='anahtar')),
                ('name', models.CharField(max_length=120, verbose_name='ad')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS')], default='whatsapp', max_length=20, verbose_name='kanal')),
                ('locale', models.CharField(choices=[('tr', 'Türkçe'), ('en', 'İngilizce')], default='tr', max_length=5, verbose_name='dil')),
                ('type', models.CharField(choices=[('appointment', 'Randevu'), ('vaccine', 'Aşı'), ('general', 'Genel')], default='appointment', max_length=20, verbose_name='tip')),
                ('body', models.TextField(help_text='Yer tutucular: {{owner_name}}, {{pet_name}}, {{date}}, {{time}}, {{vaccine}}, {{clinic}}', verbose_name='metin')),
                ('active', models.BooleanField(default=True, verbose_name='aktif')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'Mesaj Şablonu',
                'verbose_name_plural': 'Mesaj Şablonları',
                'ordering': ['type', 'locale', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReminderRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('type', models.CharField(choices=[('appointment', 'Randevu'), ('vaccine', 'Aşı'), ('general', 'Genel')], default='appointment', max_length=20, verbose_name='tip')),
                ('name', models.CharField(max_length=120, verbose_name='ad')),
                ('offset_days', models.IntegerField(default=1, verbose_name='gün farkı (önce +/sonra -)')),
                ('active', models.BooleanField(default=True, verbose_name='aktif')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='reminders.messagetemplate', verbose_name='şablon')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'Hatırlatma Kuralı',
                'verbose_name_plural': 'Hatırlatma Kuralları',
                'ordering': ['type', '-offset_days'],
            },
        ),
        migrations.CreateModel(
            name='OutboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('kind', models.CharField(choices=[('appointment', 'Randevu'), ('vaccine', 'Aşı'), ('manual', 'Elle')], default='manual', max_length=20, verbose_name='tür')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS')], default='whatsapp', max_length=20, verbose_name='kanal')),
                ('sender_number', models.CharField(blank=True, max_length=30, verbose_name='gönderen numara')),
                ('to_phone', models.CharField(max_length=30, verbose_name='alıcı telefon')),
                ('body', models.TextField(verbose_name='mesaj')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('sent', 'Gönderildi'), ('failed', 'Başarısız'), ('cancelled', 'İptal edildi')], db_index=True, default='pending', max_length=12, verbose_name='durum')),
                ('scheduled_for', models.DateField(blank=True, null=True, verbose_name='planlanan tarih')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='gönderim zamanı')),
                ('error', models.CharField(blank=True, max_length=255, verbose_name='hata')),
                ('wa_link', models.URLField(blank=True, max_length=600, verbose_name='wa.me linki')),
                ('dedupe_key', models.CharField(blank=True, db_index=True, default='', max_length=180)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='appointments.appointment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='owners.owner', verbose_name='sahip')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='patients.patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
                ('vaccine_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='vaccines.vaccinerecord')),
            ],
            options={
                'verbose_name': 'Giden Mesaj',
                'verbose_name_plural': 'Giden Mesajlar',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('dedupe_key',), name='unique_outbound_dedupe_key')],
            },
        ),
    ]
