# Generated by Django 5.1.15 on 2026-05-30 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplate',
            name='body',
            field=models.TextField(help_text='Yer tutucular: {{owner_name}}, {{pet_name}}, {{species}}, {{date}}, {{time}}, {{vaccine}}, {{amount}}, {{clinic}}, {{phone}}', verbose_name='metin'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='type',
            field=models.CharField(choices=[('appointment', 'Randevu'), ('vaccine', 'Aşı'), ('control', 'Kontrol'), ('payment', 'Tahsilat / Borç'), ('general', 'Genel')], default='appointment', max_length=20, verbose_name='tip'),
        ),
        migrations.AlterField(
            model_name='reminderrule',
            name='type',
            field=models.CharField(choices=[('appointment', 'Randevu'), ('vaccine', 'Aşı'), ('control', 'Kontrol'), ('payment', 'Tahsilat / Borç'), ('general', 'Genel')], default='appointment', max_length=20, verbose_name='tip'),
        ),
    ]
