# Generated by Django 5.1.15 on 2026-05-29 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Riva Veteriner Kliniği', max_length=200, verbose_name='klinik adı')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clinic/', verbose_name='logo')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-posta')),
                ('address', models.TextField(blank=True, verbose_name='adres')),
                ('weekday_hours', models.CharField(blank=True, max_length=40, verbose_name='hafta içi saatleri')),
                ('sunday_hours', models.CharField(blank=True, max_length=40, verbose_name='pazar saatleri')),
                ('sender_numbers', models.JSONField(blank=True, default=list, verbose_name='gönderen numaralar')),
                ('tax_office', models.CharField(blank=True, max_length=120, verbose_name='vergi dairesi')),
                ('tax_number', models.CharField(blank=True, max_length=40, verbose_name='vergi/TC no')),
            ],
            options={
                'verbose_name': 'Klinik Ayarları',
                'verbose_name_plural': 'Klinik Ayarları',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Oluşturma'), ('update', 'Güncelleme'), ('delete', 'Silme')], max_length=10)),
                ('model_label', models.CharField(max_length=120)),
                ('object_id', models.CharField(max_length=64)),
                ('object_repr', models.CharField(max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Denetim Kaydı',
                'verbose_name_plural': 'Denetim Kayıtları',
                'ordering': ['-created_at'],
            },
        ),
    ]
