# Generated by Django 5.1.15 on 2026-05-30 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='şablon adı')),
                ('complaint', models.TextField(blank=True, verbose_name='şikayet')),
                ('anamnesis', models.TextField(blank=True, verbose_name='anamnez')),
                ('findings', models.TextField(blank=True, verbose_name='bulgular')),
                ('diagnosis', models.TextField(blank=True, verbose_name='tanı')),
                ('treatment_plan', models.TextField(blank=True, verbose_name='tedavi planı')),
                ('active', models.BooleanField(default=True, verbose_name='aktif')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'Muayene Şablonu',
                'verbose_name_plural': 'Muayene Şablonları',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('complaint', models.TextField(blank=True, verbose_name='şikayet')),
                ('anamnesis', models.TextField(blank=True, verbose_name='anamnez')),
                ('findings', models.TextField(blank=True, verbose_name='bulgular')),
                ('diagnosis', models.TextField(blank=True, verbose_name='tanı')),
                ('treatment_plan', models.TextField(blank=True, verbose_name='tedavi planı')),
                ('notes', models.TextField(blank=True, verbose_name='notlar')),
                ('follow_up_date', models.DateField(blank=True, null=True, verbose_name='kontrol tarihi')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examinations', to='appointments.appointment', verbose_name='randevu')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='patients.patient', verbose_name='hayvan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
                ('vet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examinations', to=settings.AUTH_USER_MODEL, verbose_name='hekim')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examinations', to='medical.examinationtemplate', verbose_name='şablon')),
            ],
            options={
                'verbose_name': 'Muayene',
                'verbose_name_plural': 'Muayeneler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('test_name', models.CharField(max_length=160, verbose_name='test adı')),
                ('date', models.DateField(verbose_name='tarih')),
                ('result_note', models.TextField(blank=True, verbose_name='sonuç notu')),
                ('file', models.FileField(blank=True, null=True, upload_to='lab-results/', verbose_name='dosya')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('examination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results', to='medical.examination', verbose_name='muayene')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='patients.patient', verbose_name='hayvan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'Laboratuvar Sonucu',
                'verbose_name_plural': 'Laboratuvar Sonuçları',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('body', models.TextField(verbose_name='not')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_notes', to='patients.patient', verbose_name='hayvan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'Tıbbi Not',
                'verbose_name_plural': 'Tıbbi Notlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('date', models.DateTimeField(verbose_name='tarih/saat')),
                ('type', models.CharField(max_length=160, verbose_name='operasyon tipi')),
                ('anesthesia_info', models.TextField(blank=True, verbose_name='anestezi bilgisi')),
                ('drugs_used', models.TextField(blank=True, verbose_name='kullanılan ilaçlar')),
                ('result', models.TextField(blank=True, verbose_name='sonuç')),
                ('notes', models.TextField(blank=True, verbose_name='notlar')),
                ('follow_up_date', models.DateField(blank=True, null=True, verbose_name='kontrol tarihi')),
                ('post_op_instructions', models.TextField(blank=True, verbose_name='operasyon sonrası talimatlar')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='patients.patient', verbose_name='hayvan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
                ('vet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to=settings.AUTH_USER_MODEL, verbose_name='hekim')),
            ],
            options={
                'verbose_name': 'Operasyon',
                'verbose_name_plural': 'Operasyonlar',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('notes', models.TextField(blank=True, verbose_name='notlar')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('examination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='medical.examination', verbose_name='muayene')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patient', verbose_name='hayvan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
                ('vet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to=settings.AUTH_USER_MODEL, verbose_name='hekim')),
            ],
            options={
                'verbose_name': 'Reçete',
                'verbose_name_plural': 'Reçeteler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=160, verbose_name='ilaç')),
                ('dose', models.CharField(blank=True, max_length=120, verbose_name='doz')),
                ('frequency', models.CharField(blank=True, max_length=120, verbose_name='sıklık')),
                ('duration', models.CharField(blank=True, max_length=120, verbose_name='süre')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='not')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='medical.prescription', verbose_name='reçete')),
            ],
            options={
                'verbose_name': 'Reçete Kalemi',
                'verbose_name_plural': 'Reçete Kalemleri',
            },
        ),
    ]
