# Generated by Django 5.1.15 on 2026-05-29 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='tür')),
                ('active', models.BooleanField(default=True, verbose_name='aktif')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'Tür',
                'verbose_name_plural': 'Türler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('name', models.CharField(max_length=80, verbose_name='hayvan adı')),
                ('breed', models.CharField(blank=True, max_length=80, verbose_name='ırk')),
                ('sex', models.CharField(choices=[('male', 'Erkek'), ('female', 'Dişi'), ('unknown', 'Bilinmiyor')], default='unknown', max_length=10, verbose_name='cinsiyet')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='doğum tarihi')),
                ('age_text', models.CharField(blank=True, help_text="Doğum tarihi yoksa ör. '3 yaşında'", max_length=40, verbose_name='yaş (metin)')),
                ('microchip_no', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='mikroçip no')),
                ('neutered', models.CharField(choices=[('yes', 'Evet'), ('no', 'Hayır'), ('unknown', 'Bilinmiyor')], default='unknown', max_length=10, verbose_name='kısırlaştırma')),
                ('color', models.CharField(blank=True, max_length=60, verbose_name='renk')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='kilo (kg)')),
                ('allergies', models.TextField(blank=True, verbose_name='alerjiler')),
                ('chronic_conditions', models.TextField(blank=True, verbose_name='kronik hastalıklar')),
                ('notes', models.TextField(blank=True, verbose_name='özel notlar')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='patients/', verbose_name='fotoğraf')),
                ('deceased', models.BooleanField(default=False, verbose_name='vefat etti')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='owners.owner', verbose_name='sahip')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='patients.species', verbose_name='tür')),
            ],
            options={
                'verbose_name': 'Hayvan',
                'verbose_name_plural': 'Hayvanlar',
                'ordering': ['name'],
            },
        ),
    ]
