# Generated by Django 5.1.15 on 2026-05-30 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('phone_snapshot', models.CharField(blank=True, max_length=30, verbose_name='telefon')),
                ('starts_at', models.DateTimeField(db_index=True, verbose_name='tarih/saat')),
                ('duration_min', models.PositiveSmallIntegerField(default=30, verbose_name='süre (dk)')),
                ('type', models.CharField(choices=[('general', 'Genel muayene'), ('vaccine', 'Aşı'), ('control', 'Kontrol'), ('emergency', 'Acil'), ('surgery', 'Cerrahi'), ('consult', 'Danışma'), ('other', 'Diğer')], default='general', max_length=20, verbose_name='tip')),
                ('status', models.CharField(choices=[('requested', 'Talep geldi'), ('confirmed', 'Onaylandı'), ('arrived', 'Geldi'), ('in_exam', 'Muayenede'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal'), ('no_show', 'Gelmedi')], db_index=True, default='confirmed', max_length=20, verbose_name='durum')),
                ('note', models.TextField(blank=True, verbose_name='not')),
                ('assigned_vet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='atanan hekim')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='owners.owner', verbose_name='sahip')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient', verbose_name='hayvan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'Randevu',
                'verbose_name_plural': 'Randevular',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('name', models.CharField(max_length=160, verbose_name='ad soyad')),
                ('phone', models.CharField(max_length=30, verbose_name='telefon')),
                ('pet_name', models.CharField(blank=True, max_length=80, verbose_name='hayvan adı')),
                ('pet_species', models.CharField(blank=True, max_length=60, verbose_name='hayvan türü')),
                ('requested_at', models.CharField(blank=True, max_length=120, verbose_name='talep edilen tarih/saat')),
                ('subject', models.CharField(blank=True, max_length=120, verbose_name='konu')),
                ('message', models.TextField(blank=True, verbose_name='mesaj')),
                ('source', models.CharField(choices=[('web', 'Web sitesi'), ('manual', 'Elle')], default='web', max_length=10, verbose_name='kaynak')),
                ('status', models.CharField(choices=[('new', 'Yeni'), ('converted', 'Randevuya çevrildi'), ('dismissed', 'Yok sayıldı')], db_index=True, default='new', max_length=12, verbose_name='durum')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('linked_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_request', to='appointments.appointment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'Randevu Talebi',
                'verbose_name_plural': 'Randevu Talepleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
