# Generated by Django 5.1.15 on 2026-05-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reminder_enabled',
            field=models.BooleanField(default=True, help_text='Kapalıysa bu randevu için otomatik hatırlatma üretilmez.', verbose_name='hatırlatma oluştur'),
        ),
    ]
