# Generated by Django 5.1.15 on 2026-06-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_reminder_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='source',
            field=models.CharField(choices=[('scheduled', 'Planlı'), ('walk_in', 'Hızlı kabul'), ('online_request', 'Online talep'), ('auto_followup', 'Otomatik (sonraki doz)')], db_index=True, default='scheduled', max_length=20, verbose_name='kaynak'),
        ),
    ]
