# Generated by Django 5.1.15 on 2026-06-06 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_source'),
        ('vaccines', '0002_vaccinedefinition_series_doses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='dose_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='doz no'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='protocol_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='vaccines.vaccinedefinition', verbose_name='protokol'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='type',
            field=models.CharField(choices=[('general', 'Genel muayene'), ('vaccine', 'Aşı'), ('parasite', 'Parazit'), ('medication', 'İlaç / Tedavi'), ('control', 'Kontrol'), ('emergency', 'Acil'), ('surgery', 'Cerrahi'), ('consult', 'Danışma'), ('other', 'Diğer')], default='general', max_length=20, verbose_name='tip'),
        ),
    ]
