# Generated by Django 5.1.15 on 2026-05-29 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('first_name', models.CharField(max_length=80, verbose_name='ad')),
                ('last_name', models.CharField(max_length=80, verbose_name='soyad')),
                ('phone', models.CharField(db_index=True, max_length=30, verbose_name='telefon')),
                ('tc_no', models.CharField(blank=True, max_length=11, verbose_name='T.C. kimlik no')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-posta')),
                ('address', models.TextField(blank=True, verbose_name='adres')),
                ('il', models.CharField(blank=True, max_length=50, verbose_name='il')),
                ('ilce', models.CharField(blank=True, max_length=50, verbose_name='ilçe')),
                ('notes', models.TextField(blank=True, verbose_name='notlar')),
                ('contact_pref', models.CharField(choices=[('phone', 'Telefon'), ('whatsapp', 'WhatsApp'), ('email', 'E-posta'), ('none', 'İletişim istemiyor')], default='whatsapp', max_length=20, verbose_name='iletişim tercihi')),
                ('kvkk_consent', models.BooleanField(default=False, verbose_name='KVKK onayı')),
                ('kvkk_consent_at', models.DateTimeField(blank=True, null=True, verbose_name='KVKK onay tarihi')),
                ('marketing_consent', models.BooleanField(default=False, verbose_name='ticari ileti izni')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'Sahip',
                'verbose_name_plural': 'Sahipler',
                'ordering': ['first_name', 'last_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='owners_owne_last_na_785e9c_idx')],
            },
        ),
    ]
