# Generated by Django 5.1.15 on 2026-05-30 01:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('name', models.CharField(max_length=160, verbose_name='aşı adı')),
                ('first_dose_age_text', models.CharField(blank=True, max_length=120, verbose_name='ilk doz yaşı')),
                ('repeat_interval_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='tekrar aralığı (gün)')),
                ('reminder_offset_days', models.PositiveIntegerField(default=7, verbose_name='hatırlatma öncesi (gün)')),
                ('description', models.TextField(blank=True, verbose_name='açıklama')),
                ('active', models.BooleanField(default=True, verbose_name='aktif')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vaccine_definitions', to='patients.species', verbose_name='tür')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'Aşı Protokolü',
                'verbose_name_plural': 'Aşı Protokolleri',
                'ordering': ['species__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VaccineRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('vaccine_name', models.CharField(blank=True, max_length=160, verbose_name='aşı adı')),
                ('applied_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='uygulama tarihi')),
                ('next_due_at', models.DateField(blank=True, db_index=True, null=True, verbose_name='sonraki tarih')),
                ('serial_lot', models.CharField(blank=True, max_length=80, verbose_name='seri/lot')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='son kullanma tarihi')),
                ('note', models.TextField(blank=True, verbose_name='not')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_records', to='patients.patient', verbose_name='hayvan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
                ('vaccine_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='vaccines.vaccinedefinition', verbose_name='protokol')),
                ('vet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccine_records', to=settings.AUTH_USER_MODEL, verbose_name='hekim')),
            ],
            options={
                'verbose_name': 'Aşı Kaydı',
                'verbose_name_plural': 'Aşı Kayıtları',
                'ordering': ['-applied_at', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='vaccinedefinition',
            constraint=models.UniqueConstraint(fields=('name', 'species'), name='unique_vaccine_definition_species'),
        ),
    ]
