# Generated by Django 5.1.15 on 2026-05-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinedefinition',
            name='series_doses',
            field=models.PositiveSmallIntegerField(default=1, help_text='Örn. yavru karma için 2-3. 1 ise tek doz + rapel.', verbose_name='birincil seri doz sayısı'),
        ),
        migrations.AddField(
            model_name='vaccinedefinition',
            name='series_interval_days',
            field=models.PositiveIntegerField(blank=True, help_text='Birincil serideki dozlar arası gün (ör. 21). Boşsa tekrar aralığı kullanılır.', null=True, verbose_name='seri doz aralığı (gün)'),
        ),
        migrations.AlterField(
            model_name='vaccinedefinition',
            name='repeat_interval_days',
            field=models.PositiveIntegerField(blank=True, help_text='Birincil seri tamamlandıktan sonraki rapel aralığı (ör. yıllık = 365).', null=True, verbose_name='tekrar aralığı (gün)'),
        ),
    ]
