# Generated by Django 5.1.15 on 2026-06-06 10:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('vaccines', '0002_vaccinedefinition_series_doses_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaccinedefinition',
            options={'ordering': ['category', 'species__name', 'name'], 'verbose_name': 'Protokol', 'verbose_name_plural': 'Protokoller'},
        ),
        migrations.RemoveConstraint(
            model_name='vaccinedefinition',
            name='unique_vaccine_definition_species',
        ),
        migrations.AddField(
            model_name='vaccinedefinition',
            name='category',
            field=models.CharField(choices=[('vaccine', 'Aşı'), ('internal_parasite', 'İç Parazit'), ('external_parasite', 'Dış Parazit'), ('medication', 'İlaç / Tedavi')], db_index=True, default='vaccine', max_length=20, verbose_name='kategori'),
        ),
        migrations.AlterField(
            model_name='vaccinedefinition',
            name='name',
            field=models.CharField(max_length=160, verbose_name='ad'),
        ),
        migrations.AddConstraint(
            model_name='vaccinedefinition',
            constraint=models.UniqueConstraint(fields=('name', 'species', 'category'), name='unique_vaccine_definition_species'),
        ),
    ]
